import { useEffect, useState } from 'react';
import { ArrowDown, ArrowUp, Boxes, X } from 'lucide-react';
import { supabase } from './lib/supabase';

export default function InventoryPage({ store }) {
  const [products,setProducts]=useState([]); const [history,setHistory]=useState([]); const [selected,setSelected]=useState(null); const [quantity,setQuantity]=useState(''); const [reason,setReason]=useState(''); const [mode,setMode]=useState('add'); const [message,setMessage]=useState('');
  const load=async()=>{const [{data:p},{data:h}]=await Promise.all([supabase.from('products').select('id,name,sku,stock,color').eq('store_id',store.id).eq('is_active',true).order('stock'),supabase.from('inventory_adjustments').select('id,quantity_change,stock_before,stock_after,reason,created_at,products(name,sku)').eq('store_id',store.id).order('created_at',{ascending:false}).limit(30)]);setProducts(p||[]);setHistory(h||[]);}; useEffect(()=>{if(store)load();},[store]);
  const adjust=async(e)=>{e.preventDefault();setMessage('');const delta=Math.abs(Number(quantity))*(mode==='add'?1:-1);const {error}=await supabase.rpc('adjust_product_stock',{target_product:selected.id,quantity_delta:delta,adjustment_reason:reason});if(error)return setMessage(error.message);setSelected(null);setQuantity('');setReason('');load();};
  return <section className="management-page"><div className="management-head"><div><span className="eyebrow">Stock control</span><h2>Inventory</h2><p>Review stock levels and keep an audit trail of every adjustment.</p></div></div><div className="inventory-summary"><div><Boxes/><span><b>{products.length}</b>Products tracked</span></div><div><ArrowDown/><span><b>{products.filter(p=>p.stock<=10).length}</b>Low-stock items</span></div><div><ArrowUp/><span><b>{products.reduce((n,p)=>n+p.stock,0)}</b>Total units</span></div></div>
    <div className="inventory-layout"><article className="inventory-products"><h3>Stock levels</h3>{products.map(p=><button key={p.id} onClick={()=>{setSelected(p);setMessage('')}}><span className="table-art" style={{background:`${p.color}18`,color:p.color}}>{p.name.slice(0,2).toUpperCase()}</span><span><b>{p.name}</b><small>{p.sku}</small></span><strong className={p.stock<=10?'stock-warning':''}>{p.stock}</strong></button>)}</article><article className="inventory-history"><h3>Adjustment history</h3>{!history.length?<p className="empty-history">No manual adjustments yet.</p>:history.map(item=><div key={item.id}><span><b>{item.products?.name}</b><small>{item.reason} · {new Date(item.created_at).toLocaleString()}</small></span><strong className={item.quantity_change>0?'positive':'negative'}>{item.quantity_change>0?'+':''}{item.quantity_change}</strong><small>{item.stock_before} → {item.stock_after}</small></div>)}</article></div>
    {selected&&<div className="modal-backdrop"><form className="manage-modal compact" onSubmit={adjust}><div className="manage-modal-head"><div><span className="eyebrow">Inventory adjustment</span><h3>{selected.name}</h3></div><button type="button" onClick={()=>setSelected(null)}><X/></button></div><div className="adjust-tabs"><button type="button" className={mode==='add'?'active':''} onClick={()=>setMode('add')}><ArrowUp/>Stock in</button><button type="button" className={mode==='remove'?'active':''} onClick={()=>setMode('remove')}><ArrowDown/>Stock out</button></div><label className="full-label">Quantity<input required min="1" type="number" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><label className="full-label">Reason<input required minLength="2" value={reason} onChange={e=>setReason(e.target.value)} placeholder="e.g. New delivery, damaged item"/></label>{message&&<p className="management-error">{message}</p>}<button className="save-button">Save adjustment</button></form></div>}
  </section>;
}
