import { useEffect, useState } from 'react';
import { Edit3, Package, Plus, Search, Trash2, X } from 'lucide-react';
import { supabase } from './lib/supabase';

const emptyForm = { name: '', sku: '', price: '', stock: '', category_id: '', color: '#2563eb' };
const money = (value) => `Rs. ${Number(value).toLocaleString('en-PK')}`;

export default function ProductsPage({ store }) {
  const [products, setProducts] = useState([]); const [categories, setCategories] = useState([]); const [search, setSearch] = useState('');
  const [form, setForm] = useState(emptyForm); const [editing, setEditing] = useState(null); const [open, setOpen] = useState(false); const [message, setMessage] = useState('');
  const load = async () => { const [{ data: productRows }, { data: categoryRows }] = await Promise.all([supabase.from('products').select('id,name,sku,price,stock,color,is_active,category_id,categories(name)').eq('store_id', store.id).eq('is_active', true).order('name'), supabase.from('categories').select('id,name').eq('store_id', store.id).order('sort_order')]); setProducts(productRows || []); setCategories(categoryRows || []); };
  useEffect(() => { if (store) load(); }, [store]);
  const showForm = (product = null) => { setEditing(product); setForm(product ? { name: product.name, sku: product.sku, price: product.price, stock: product.stock, category_id: product.category_id || '', color: product.color } : emptyForm); setMessage(''); setOpen(true); };
  const save = async (event) => { event.preventDefault(); setMessage(''); const payload = { store_id: store.id, name: form.name.trim(), sku: form.sku.trim().toUpperCase(), price: Number(form.price), stock: Number(form.stock), category_id: form.category_id ? Number(form.category_id) : null, color: form.color };
    const { error } = editing ? await supabase.from('products').update(payload).eq('id', editing.id) : await supabase.from('products').insert(payload); if (error) return setMessage(error.message); setOpen(false); load(); };
  const archive = async (product) => { if (!window.confirm(`Archive ${product.name}?`)) return; const { error } = await supabase.from('products').update({ is_active: false }).eq('id', product.id); if (error) setMessage(error.message); else load(); };
  const filtered = products.filter((item) => `${item.name} ${item.sku}`.toLowerCase().includes(search.toLowerCase()));
  return <section className="management-page"><div className="management-head"><div><span className="eyebrow">Catalog</span><h2>Products</h2><p>Manage items, prices, categories and available stock.</p></div><button onClick={() => showForm()}><Plus size={17}/> Add product</button></div>
    <div className="management-toolbar"><div className="manage-search"><Search size={17}/><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search products or SKU"/></div><span>{filtered.length} active products</span></div>{message && <p className="management-error">{message}</p>}
    <div className="product-table"><div className="product-row product-row-head"><span>Product</span><span>Category</span><span>Price</span><span>Stock</span><span>Actions</span></div>{filtered.map((product) => <div className="product-row" key={product.id}><div className="product-cell"><span className="table-art" style={{background:`${product.color}18`,color:product.color}}>{product.name.slice(0,2).toUpperCase()}</span><span><b>{product.name}</b><small>{product.sku}</small></span></div><span>{product.categories?.name || 'Uncategorized'}</span><b>{money(product.price)}</b><span className={product.stock <= 10 ? 'stock-warning' : ''}>{product.stock} units</span><div className="row-actions"><button onClick={() => showForm(product)}><Edit3 size={15}/></button><button onClick={() => archive(product)}><Trash2 size={15}/></button></div></div>)}</div>
    {open && <div className="modal-backdrop"><form className="manage-modal" onSubmit={save}><div className="manage-modal-head"><div><span className="eyebrow">{editing ? 'Update item' : 'New item'}</span><h3>{editing ? 'Edit product' : 'Add product'}</h3></div><button type="button" onClick={() => setOpen(false)}><X size={19}/></button></div><div className="form-grid"><label>Product name<input required value={form.name} onChange={(e) => setForm({...form,name:e.target.value})}/></label><label>SKU<input required value={form.sku} onChange={(e) => setForm({...form,sku:e.target.value})}/></label><label>Price<input required min="0" step="0.01" type="number" value={form.price} onChange={(e) => setForm({...form,price:e.target.value})}/></label><label>Opening stock<input required min="0" type="number" value={form.stock} onChange={(e) => setForm({...form,stock:e.target.value})}/></label><label>Category<select value={form.category_id} onChange={(e) => setForm({...form,category_id:e.target.value})}><option value="">Uncategorized</option>{categories.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Card color<input type="color" value={form.color} onChange={(e) => setForm({...form,color:e.target.value})}/></label></div>{message && <p className="management-error">{message}</p>}<button className="save-button"><Package size={17}/>{editing ? 'Save changes' : 'Create product'}</button></form></div>}
  </section>;
}
