import { useEffect, useState } from 'react';
import { Mail, RotateCcw, Search, X } from 'lucide-react';
import { supabase } from './lib/supabase';
import { apiUrl } from './lib/api';
const money=v=>`Rs. ${Number(v||0).toLocaleString('en-PK')}`;
export default function SalesPage({store}){const[sales,setSales]=useState([]),[search,setSearch]=useState(''),[selected,setSelected]=useState(null),[reverse,setReverse]=useState(null),[reason,setReason]=useState(''),[message,setMessage]=useState('');
const load=async()=>{const{data,error}=await supabase.from('sales').select('id,subtotal,tax,discount,total,status,note,created_at,sale_items(product_name,sku,quantity,unit_price),payments(kind,tendered,change_due)').eq('store_id',store.id).order('created_at',{ascending:false}).limit(100);if(error)setMessage(error.message);else setSales(data||[])};useEffect(()=>{if(store)load()},[store]);
const doReverse=async()=>{const{error}=await supabase.rpc('reverse_sale',{target_sale:selected.id,reversal_status:reverse,reversal_reason:reason});if(error)return setMessage(error.message);setReverse(null);setReason('');setSelected(null);load()};
const resend=async sale=>{setMessage('Sending receipt…');const{data}=await supabase.auth.getSession();const receipt={...sale,paymentMethod:sale.payments?.[0]?.kind||'other',items:sale.sale_items.map(i=>({name:i.product_name,price:Number(i.unit_price),quantity:i.quantity}))};const response=await fetch(apiUrl('/api/email/receipt'),{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.session?.access_token}`},body:JSON.stringify({storeName:store.name,receipt})});const result=await response.json().catch(()=>({}));setMessage(response.ok?`Receipt sent to ${result.to}`:result.message||'Email failed')};
const filtered=sales.filter(s=>String(s.id).includes(search));return <section className="management-page"><div className="management-head"><div><span className="eyebrow">Transactions</span><h2>Sales history</h2><p>Review orders, resend receipts and reverse completed sales.</p></div></div><div className="management-toolbar"><div className="manage-search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search order number"/></div><span>{filtered.length} transactions</span></div>{message&&<p className="management-error">{message}</p>}<div className="product-table"><div className="sale-row sale-row-head"><span>Order</span><span>Date</span><span>Payment</span><span>Status</span><span>Total</span></div>{filtered.map(s=><button className="sale-row" key={s.id} onClick={()=>{setSelected(s);setMessage('')}}><b>#{s.id}</b><span>{new Date(s.created_at).toLocaleString()}</span><span>{s.payments?.[0]?.kind||'—'}</span><span className={`status ${s.status}`}>{s.status}</span><strong>{money(s.total)}</strong></button>)}</div>{selected&&<div className="modal-backdrop"><div className="manage-modal sale-detail"><div className="manage-modal-head"><div><span className="eyebrow">Transaction details</span><h3>Order #{selected.id}</h3></div><button onClick={()=>setSelected(null)}><X/></button></div><p>{new Date(selected.created_at).toLocaleString()} · {selected.payments?.[0]?.kind}</p><div className="detail-items">{selected.sale_items.map((i,index)=><div key={index}><span>{i.quantity} × {i.product_name}<small>{i.sku}</small></span><b>{money(i.quantity*Number(i.unit_price))}</b></div>)}</div><div className="detail-totals"><div><span>Subtotal</span><b>{money(selected.subtotal)}</b></div><div><span>Tax</span><b>{money(selected.tax)}</b></div><div><span>Discount</span><b>- {money(selected.discount)}</b></div><div><span>Total</span><strong>{money(selected.total)}</strong></div></div><button className="outline-action" onClick={()=>resend(selected)}><Mail/>Resend receipt</button>{selected.status==='completed'&&!reverse&&<div className="reverse-actions"><button onClick={()=>setReverse('voided')}>Void sale</button><button onClick={()=>setReverse('refunded')}><RotateCcw/>Refund & restock</button></div>}{reverse&&<div className="reverse-box"><label>Reason<input autoFocus value={reason} onChange={e=>setReason(e.target.value)} placeholder={`Reason for ${reverse}`}/></label><div><button onClick={()=>setReverse(null)}>Cancel</button><button disabled={reason.trim().length<2} onClick={doReverse}>Confirm {reverse}</button></div></div>}</div></div>}</section>}
